### PR TITLE
Add GIF/MP4 generation for layout optimization visualization

### PR DESCRIPTION
**Pull request by I-am-zeroZ**
- Implemented a feature to visualize the layout optimization process as GIF/MP4.
- Added `GenGIF.py` to handle input arguments and invoke visualization functions.
- Enhanced `layout_parser.py` to correctly parse `.lg`, `.opt`, and `.postlg` files with support for merged FFs.
- Updated `layout_visualizer.py` to progressively remove merged FFs and add the newly created MBFFs during visualization.
- Introduced a `draw_cell` function to render layout cells on a Matplotlib axis.
- Included `generate_animation` in `layout_visualizer.py` to compile visualization frames into a GIF/MP4.
- Updated `requirements.txt` to list dependencies (`matplotlib`, `Pillow`, `argparse`).
- Verified feasibility on self-generated small test cases, but functionality on larger test cases like `testcase1_16900` is unverified due to longer runtime.

### CODE REVIEW

**Comment by coherent17** [comment]
Hi can you add the usage and provide the sample of this program?

**Comment by coherent17** [comment]
Single file of code should cover this, can you make them in one file?

**Comment by coherent17** [comment]
How long will it need to run our public testcase, can you show me the result of the public testcase? I will review your work at night, thanks!

**Comment by I-am-zeroZ** [comment]
Thank you for your suggestions!

1. I have merged all Python modules into a single file (`GenGIF.py`) as requested. This file now includes all functionality, such as parsing input files, generating visualizations, and creating GIF/MP4 outputs.

2. I have also added usage instructions and provided small-scale test cases (`testcase0` and `testcase0_c`) along with their corresponding input files (`.lg`, `.opt`, `.postlg`). Additionally, I have included the generated GIF outputs (`testcase0.gif`, `testcase0_c.gif`) to demonstrate the program's functionality.

3. Regarding the public test case runtime, it is difficult to estimate accurately at this point. For instance, when running `testcase1_16900` on the server, the program has been executing for over an hour without completing. This indicates that there might be room for optimization in the implementation.
Additionally, I suspect that the generated GIF may face challenges in maintaining visual precision due to the large die size and the significant number of cells in this test case. If you have any suggestions or specific areas to focus on for optimization, I'd be happy to look into them.

Please let me know if there's anything else you'd like me to adjust or clarify.

---
### My Current Thoughts

1. It is practically impossible to annotate text on cells. In large test cases, the text size would either be too small to read or so large that it would overlap the cells, making the entire layout appear as a dense black mass.

2. Using MP4 instead of GIF: Even if each move lasts only one frame (1/60 of a second), the output file for a case like `testcase1_ALL0_5000` would still result in a video of 57 seconds. Therefore, compared to GIF, using MP4 or a lossless compressed video format might be a better option for storage.

**Comment by coherent17** [comment]
Hi, the runtime and the quality should be one of the concern. However, this should be a good start for others to enhance the implementation. Will review it at night and try to merge it if possible!

**Comment by I-am-zeroZ** [comment]
I added `GenMP4.py`. This script uses `FFmpeg` for video processing. However, please note that FFmpeg is not a Python package and cannot be installed via `pip install ffmpeg`. Even without administrator privileges and the ability to install it using `sudo apt`, you can still manually download the precompiled binary files for FFmpeg and add them to the PATH environment variable.
### **Current Performance Bottleneck: `visualize_steps`**

#### **Function Overview**
The `visualize_steps` function processes layout optimization steps by iteratively updating the current list of cells and generating frames for visualization. This involves:
1. Removing merged cells.
2. Adding newly generated cells.
3. Creating frames for each intermediate state.

---

#### **Current Implementation Analysis**

In the current implementation:
- `current_cells` is stored as a **list**.
- Removing a cell involves searching the list and removing the corresponding element (O(N)).
- Adding a new cell is a simple append operation (O(1)).

**Time Complexity**:
- For each optimization step, updating the list involves:
  - Removing k cells (O(k * N), where k is the number of inputs in the step).
  - Adding a new cell (O(1)).

With M optimization steps:
O(M * N)
Where N is the number of cells in the layout.

---

I will try using other data structures, such as dictionary, later. This should reduce the overall time complexity of `visualize_steps` from O(M * N) to O(M).

**Comment by coherent17** [comment]
Hi, I will merge these commit, if you have more time, please help enhance the program efficiency.
Also, please generate the readme for the usage.
Thanks

**Comment by I-am-zeroZ** [comment]
After that, I’ve tried various optimization methods, such as reusing the previous frame and only redrawing the cells that were moved, deleted, or added. 
However, the rendering efficiency is still relatively slow.
For larger test cases, rendering a single frame takes approximately 15 seconds, and with the total number of frames being equivalent to the number of .opt file lines +1, the overall performance significantly lags behind other impressive methods shared by others, such as those utilizing OpenGL or web-based visualization.

That said, I will still upload the optimized and bug-fixed version of `GenMP4.py` via a PR later, along with the final execution results.

Additionally, I might include a `README` file for better clarity.

**Comment by coherent17** [comment]
Hi,

I think you can focus on gif, the MP4 has been generated with relative high quality and speed!

And I think you can update per frame on 10-20 opt steps. Will that be more efficient?

Thanks
Coherent

**Comment by I-am-zeroZ** [comment]
The performance difference between the drawing functions is too significant. If I were to improve the GIF generation feature, I would prefer to base it on the code provided by @XCI9

**Comment by coherent17** [comment]
Sure, you can reference his work to enhance the quality of gif!

Thanks

**Pull request merged**
